# Generated by Django 4.0.5 on 2022-07-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default=2, max_length=50, verbose_name='Genero'),
            preserve_default=False,
        ),
    ]
